version: '2'
services:

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    networks:
      - ldap
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=redmine'
  redmine:
    container_name: redmine
    image: redmine:latest
    restart: always
    networks:
      - ldap
    volumes:
      - redmine-data:/usr/src/redmine/files
    ports:
      - 8099:3000
    environment:
      - 'REDMINE_DB_POSTGRES=postgres'
      - 'REDMINE_DB_DATABASE=redmine'
      - 'REDMINE_DB_PASSWORD=password'
    links:
      - postgres
networks:
  ldap:
    driver: bridge


volumes:
  postgres-data:
  redmine-data: